packages:
  - "apps/*"
  - "middlewares/*"
  - "sdks/typescript/packages/*"
  - "integrations/*/typescript"
  - "integrations/community/*/typescript"
  - "integrations/mastra/typescript/examples"

ignoredBuiltDependencies:
  - "@scarf/scarf"
  - "@tailwindcss/oxide"
  - "esbuild"
  - "protobufjs"
  - "sharp"
  - "unrs-resolver"
